version: '2'
services:
  camera1:
    container_name: camera1
    image: irbp/ffserver
    ports:
      - 554:554
      - 8090:80
    volumes:
      - ./docker/ffserver/ffserver.conf:/etc/ffserver.conf
      - ./docker/data:/data

  camera1-source:
    container_name: camera1-source
    build:
      context: ./docker
      dockerfile: ./ffmpeg/Dockerfile
    depends_on: 
      - camera1
    volumes:
      - ./docker/data:/data
    environment:
      FEED_URL: http://camera1/feed.ffm
      VIDEO_PATH: /data/video.mp4

  producer:
    container_name: producer
    build: .
    depends_on:
      - camera1
    environment:
      KAFKA_URL: kafka:29092
      KAFKA_TOPIC: frames
      SOURCE_URLS: http://camera1/live.mjpg
    networks:
      - default
      - server_network

# Allows communication between this network and server network
# server_network is specified on server docker-compose.yml
networks:
  server_network:
    external: true
